### ISSUE TITLE
CLOUD - mobile view menu icon removed

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_cloud#12]
Need to remove menu icon from mobile view
![IMAGE 2021-02-17 16:10:11](https://user-images.githubusercontent.com/20182572/108215991-9cf0ca00-713a-11eb-9590-21051113ab69.jpg)
 as we don't have navbar secition there yet.

**Comment by ehab-hassan** [comment]
done at staging
https://www2.cloud.threefold.io/
