### ISSUE TITLE
CLOUD: Add Header & Footer

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_cloud#15]
Need to add header & footer. Will work with Kristine directly on this. Fits in with other issue on getting four new pages live.

**Comment by Sacha96** [comment]
**HEADER**

- Logo (Home)
- Learn >>> https://new.threefold.io/info/cloud#/
- Build >>> https://vdc.testnet.grid.tf/vdc/#/
- Forum >>> https://forum.threefold.io
- More >>> Team - Partners - Newsroom - Blog

**FOOTER**

Learn

- ​​​​​​​​​​​​​​Knowledge Base >>> https://new.threefold.io/info/cloud#/cloud__evdc_marketplace
- About ThreeFold >>> https://threefold.io
- ThreeFold Marketplace >>> https://new.threefold.io/marketplace
- ThreeFold Token >>> https://farming.threefold.io/token

Participate

- Get Started >>> https://new.threefold.io/info/cloud#/cloud__evdc_getting_started​​​​​​​​​​​​​​​​​​​​​
- Pricing >>> https://new.threefold.io/info/cloud#/cloud__evdc_pricing
- How to Get TFT >>> https://new.threefold.io/info/threefold#/threefold__how_to_buy_and_sell
- Store TFT >>> https://new.threefold.io/info/threefold#/threefold__storing_tft

Community

- Join our Forum >>> https://forum.threefold.io
- Join our Test Community >>> https://bit.ly/tftesting
- Stay Updated >>> https://t.me/threefoldnews
- Contact >>> info@threefold.io

Legal

- ​​​​​​​​​​​​​​Terms & Conditions >>> https://new.threefold.io/info/legal#/legal__terms_conditions_websites
- Privacy Policy >>> https://new.threefold.io/info/legal#/legal__privacypolicy
- Impressum >>> N/A (needs to be created)

**Comment by samtaggart** [comment]
I don't see a footer on local for cloud
