### ISSUE TITLE
CLOUD: Add pricing underneath Edge Virtual Data Center

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_cloud#18]
Here is the information needed, based on the pricing component from example site repo.

https://secure.threefold.me/code/#/2/code/edit/XIq3pN7rcghl3WOSE8F8KfLK/

- [x] Kristine adds component to cloud site in correct spot
- [x] Kristine OR Sam fills in data (@Vilnite feel free to give this to me once created)

**Comment by Vilnite** [comment]
Well detailed issue, thank you. Added.
 
<img width="1185" alt="Screenshot 2021-03-19 at 13 41 39" src="https://user-images.githubusercontent.com/20182572/111775045-ead32c00-88b8-11eb-8d7b-60877f5d0f8e.png">
