### ISSUE TITLE
CLOUD: Three small changes (before Sunday's push possible?)

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_cloud#19]
- [x] Please add a button on eVDC component that says Pricing and links to the pricing component
- [x] Move pricing to the bottom and change title to Mainnet Pricing
- [x] Please add a color background to the "We are currently in BETA version" component (I'm unsure which color to use, let's try grey and maybe the turquoise from the website and sees what works

**Comment by Vilnite** [comment]
@ehab-hassan  
please add another (lighter) button to card component and link to bottom Mainnet Pricing block

<img width="1271" alt="Screenshot 2021-03-19 at 19 37 55" src="https://user-images.githubusercontent.com/20182572/111820857-a791b100-88ea-11eb-89ec-83fd7a65ffc2.png">
