### ISSUE TITLE
fix marketplace link 

### ISSUE THREAD

**Issue by hossnys** [threefoldfoundation/www_threefold_cloud#26]
As we changed the links naming and threefold.io/marketplace is not available anymore so it needs to be replaced with marketplace.threefold.io
![Screenshot_20211103-215246](https://user-images.githubusercontent.com/26298009/140183297-d1d56f50-a76e-45bd-b9ad-9ea41fe29134.jpg)

**Comment by ehab-hassan** [comment]
fixed
