### ISSUE TITLE
Add left tabbed + features component

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_cloud#3]
Can we please create a new component out of combining left tabbed info block with features component:

<img width="1111" alt="Screenshot 2021-01-11 at 12 53 41" src="https://user-images.githubusercontent.com/20182572/104171969-24e10700-540c-11eb-8dfd-62315c19beeb.png">

'+

<img width="1149" alt="Screenshot 2021-01-11 at 12 54 08" src="https://user-images.githubusercontent.com/20182572/104171977-290d2480-540c-11eb-953f-e8e90fdaea36.png">

=

![component](https://user-images.githubusercontent.com/20182572/104171990-2dd1d880-540c-11eb-9f01-01b15f91347d.jpg)

**Comment by samaradel** [comment]
we can deal with excerpt but we can't split the content inside the excerpt with markdown
